### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by UnknownNull** [cooldogedev/TNTTag#12]
![image](https://user-images.githubusercontent.com/91208232/216088269-1239a867-de6b-485e-b345-ae20a6344f03.png)

**Comment by cooldogedev** [comment]
Closing due to lack of information, create a new one when you gather more information e.g. how to reproduce the issue and what version you're on. Anyways this error should never occur otherwise would've been reported before.

**Comment by UnknownNull** [comment]
TntTag: lasted version
Pmmp: api4

**Comment by cooldogedev** [comment]
> how to reproduce

**Comment by UnknownNull** [comment]
Phar
