### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by EvilDevil1175** [cooldogedev/TNTTag#3]
Make a tutorial how to setup

**Comment by cooldogedev** [comment]
The setup is relatively easy, all you have to do is run `/tt` (or whatever you set it to in the langauge files) and you'll get the usage of the `/tt create` subcommand. Follow the usage and you'll have a working map, keep in mind this is also usable from the console itself.

**Comment by Wabit02** [comment]
please make a example like: /tnttag create tnttest 30 8 etc..

**Comment by cooldogedev** [comment]
Check out the [readme](https://github.com/cooldogedev/TNTTag#arena-creation)
