### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by EvilDevil1175** [cooldogedev/TNTTag#5]
Error: "Class "muqsit\simplepackethandler\SimplePacketHandler" not found"

**Comment by cooldogedev** [comment]
You're either using a corrupted build or trying to build it yourself without installing the required virions (Commando and SimplePacketHandler), just tested the [latest build from poggit](https://poggit.pmmp.io/r/188513/TNTTag_dev-13.phar) and it works perfectly fine.
