### ISSUE TITLE
Make a example pls like

### ISSUE THREAD

**Issue by Wabit02** [cooldogedev/TNTTag#6]

**Comment by Wabit02** [comment]
example like: /tnttag create tnt etc etc etc

**Comment by cooldogedev** [comment]
https://github.com/cooldogedev/TNTTag#example

**Comment by Wabit02** [comment]
tnt world doesnt exist do you have discord? pls

**Comment by Wabit02** [comment]
my discord its: wabit02#5127

**Comment by cooldogedev** [comment]
As the error implies, you don't have a world with that name. You're overcomplicating this.

**Comment by cooldogedev** [comment]
Make sure that the world you want to use matches with the one you're providing in the command. You can do this by renaming the world inside the worlds directory
